{\rtf1\ansi\ansicpg1252\cocoartf2818
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 .AppleSystemUIFontMonospaced-Regular;}
{\colortbl;\red255\green255\blue255;\red18\green82\blue31;\red244\green246\blue249;\red24\green26\blue30;
\red11\green34\blue86;}
{\*\expandedcolortbl;;\cssrgb\c6667\c38824\c16078;\cssrgb\c96471\c97255\c98039;\cssrgb\c12157\c13725\c15686;
\cssrgb\c3922\c18824\c41176;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs27\fsmilli13600 \cf2 \cb3 \expnd0\expndtw0\kerning0
theme:\cf4  \cf5 jekyll-theme-minimal\cf4 \
\cf2 title:\cf4  \cf5 Backing Tracks\cf4 \
\cf2 description:\cf4  }